Styled the NavBar
hatchways/team-igneous pull request #59
Opened 2021-11-02 17:38 UTC by BenLardie

### What this PR does (required):
- navbar was a skeleton now it has style.
- still will need functionality when messages are ready but the notification indicator is set up

### Screenshots / Videos (front-end only):
![Screen Shot 2021-11-02 at 1 33 58 PM](https://user-images.githubusercontent.com/44823016/139917020-72872e74-d38e-46a4-a2ba-31f0b5e2a15d.png)

### Any information needed to test this feature (required):
- its a visual test

2021-11-02 19:45 UTC, ezeilo-su requested changes
Good work with this :+1: 
#### A few things to always remember when creating PRs:
- Fill the PR template properly
- Link the issue you're addressing to your PR. Check out this [guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to see how to.

Happy Coding!

2021-11-02 19:45 UTC, ezeilo-su commented on client/src/components/AuthMenu/AuthMenu.tsx
> +    <div className={classes.navBar}>
Please use MUI `Box` component for HTML `div` element

2021-11-02 19:45 UTC, ezeilo-su commented on client/src/components/AuthMenu/AuthMenu.tsx
> +        {!!loggedInUser && (
Good to make it boolean :+1:

2021-11-02 19:54 UTC, BenLardie commented
> Good work with this 👍
> 
> #### A few things to always remember when creating PRs:
> * Fill the PR template properly
> * Link the issue you're addressing to your PR. Check out this [guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to see how to.
> 
> Happy Coding!

You are so quick! I knew I forgot to link issue so I went back to do it but you beat me.

2021-11-03 14:32 UTC, bonnieli approved these changes

2021-11-04 16:15 UTC, merged